apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kaushalpod
  name: kaushalpod
spec:
  volumes:
  - name: ani-vol
    persistentVolumeClaim:
      claimName: pvc0003     
  containers:
  - image: nginx
    name: kaushalpod
    volumeMounts:
    - name: ani-vol
      mountPath: /var/lib/
