apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: daspod1
  name: daspod1
spec:
  volumes:
  - name: anivol2
    persistentVolumeClaim:
      claimName: pv003
  containers:
  - image: nginx
    name: daspod
    volumeMounts:
    - name: anivol2
      mountPath: /var/lib/		
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
