apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: daspod2
  name: daspod2
spec:
  volumes:
  - name: anivol2
    persistentVolumeClaim:
      claimName: pv003
  containers:
  - image: nginx
    name: daspod
    volumeMounts:
    - name: anivol2
      mountPath: /var/lib/
    envFrom:
    - configMapRef:
        name: my-config		
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
