apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv003
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage
